### ISSUE TITLE
请问能否支持歌词显示(内嵌的也可以)？

### ISSUE THREAD

**Issue by 1789984734** [nini22P/omp#119]
如题，我上传的音乐都是用MusicTag补全过歌词的，如果能直接读取最好，或者LRC格式的歌词也行，感谢查看。

**Comment by nini22P** [comment]
后续会支持

**Comment by 1789984734** [comment]
好的，多谢回复，期待实现。

**Comment by nini22P** [comment]
https://github.com/user-attachments/assets/c2e59eba-3e98-4855-97ce-4628fee164f8

歌词效果预览

**Comment by 1789984734** [comment]
请问能否考虑歌词原文和翻译一起高亮的情况，原文和翻译都是同一个时间戳，感觉可以根据这个条件选择一起高亮。
![image](https://github.com/user-attachments/assets/c6ea232a-f782-4ded-86d5-5c4d6d0a3b1f)
![image](https://github.com/user-attachments/assets/0c0dca7d-5946-40cf-ba54-e067ab369910)

**Comment by nini22P** [comment]
将在下个版本支持 #123
