### ISSUE TITLE
添加音量调节按钮

### ISSUE THREAD

**Issue by feeas** [nini22P/omp#89]
可以添加音量调节按钮吗? 跟OneDrive网页一样,网页播放音乐也有音量调节,因为一些蓝牙耳机系统层面调节到最小音量都太大声,需要网页再调节音量.

**Comment by nini22P** [comment]
#90 已添加，宽度不够可能会被隐藏，手机上请使用横屏

**Comment by feeas** [comment]
十分感谢开发者这么快就添加了功能
